server:
  port: 9092
  context-path: /
  session:
    timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: '{cipher}e2299a39fef77b0eb345f71d49503a6c6dda0511d9c4283c7e12d9c1a2da0309'
      key02: value02

feign:
  hystrix:
    enabled: true

