server:
  port: 9092
  context-path: /
  session:
    timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: '{cipher}256e85c75d67b3abd48eb94948e483200710f8eeefbfcfc284f9fe4736f80315'
      key02: value02

feign:
  hystrix:
    enabled: true

