server:
  port: 9092
  context-path: /
  session:
    timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: '{cipher}AIAXY0lAVvT0TXJPapBdqpcqPwkx3+OV287BC4dJhlvVygmk66kHfQzFaYDcW00zsQ6sXLxm+SF6ZvL5kdQAuF90t8CP9KVTS6y3NW887+foak1RCzOx7VBNmxsTYWXpufxIOj5TKgZE2SJngTQB4itMxn7KFra1KbRC6DEwKhRNu+fQOKN4m2hTQkqsOWWU7i+B39OMrpurC/ztFVAum2OM'
      key02: value02

feign:
  hystrix:
    enabled: true
    

